"""
Project-level configuration: team name, season, competitions, language.
Generated by the first-run setup flow. Persists to config/project.json.
"""
import json
from pathlib import Path
from typing import Optional

CONFIG_DIR = Path(__file__).parent.parent / "config"


class ProjectConfig:
    def __init__(self):
        self._path = CONFIG_DIR / "project.json"
        self._data: Optional[dict] = None
        if self._path.exists():
            try:
                self._data = json.loads(self._path.read_text(encoding="utf-8"))
            except Exception:
                self._data = None

    @property
    def exists(self) -> bool:
        return self._data is not None

    @property
    def team_name(self) -> str:
        return (self._data or {}).get("team_name", "My Team")

    @property
    def season(self) -> str:
        return (self._data or {}).get("season", "")

    @property
    def competitions(self) -> list[str]:
        return (self._data or {}).get("competitions", [])

    @property
    def language(self) -> str:
        return (self._data or {}).get("language", "en")

    def save(self, team_name: str, season: str, competitions: list[str], language: str = "en"):
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        self._data = {
            "team_name": team_name,
            "season": season,
            "competitions": competitions,
            "language": language,
        }
        self._path.write_text(
            json.dumps(self._data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    def delete(self):
        """Remove the project config file."""
        if self._path.exists():
            self._path.unlink()
        self._data = None

    def to_dict(self) -> dict:
        if not self._data:
            return {"team_name": "My Team", "season": "", "competitions": [], "language": "en"}
        return dict(self._data)
